apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-go-sample
  name: client-go-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-go-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-go-sample
    spec:
      containers:
      - image: ashishjainjnp/basic-client:0.1.0
        name: basic-client
        resources: {}
status: {}
